question_data = [
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"The HTML5 standard was published in 2014.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"Linus Torvalds created Linux and Git.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"The logo for Snapchat is a Bell.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"Pointers were not used in the original C programming language; they were added later on in C++.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"&quot;Windows NT&quot; is a monolithic kernel.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"RAM stands for Random Access Memory.","correct_answer":"True","incorrect_answers":["False"]}, 
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"Ada Lovelace is often considered the first computer programmer.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"AMD created the first consumer 64-bit processor.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"hard","question":"DHCP stands for Dynamic Host Configuration Port.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"&quot;HTML&quot; stands for Hypertext Markup Language.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"hard","question":"The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"Early RAM was directly seated onto the motherboard and could not be easily removed.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"Time on Computers is measured via the EPOX System.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"The Windows 7 operating system has six main editions.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"The Windows ME operating system was released in the year 2000.","correct_answer":"True","incorrect_answers":["False"]},            
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"It&#039;s not possible to format a write-protected DVD-R Hard Disk.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"Linux was first created as an alternative to Windows XP.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"A Boolean value of &quot;0&quot; represents which of these words?","correct_answer":"False","incorrect_answers":["True"]}
]
